### ISSUE TITLE
[Bug]: browser_mod.popup with user_id fails on HA 2026.05 — AttributeError: module 'homeassistant.helpers.template' has no attribute 'state_attr'

### ISSUE THREAD

**Issue by davidology** [thomasloven/hass-browser_mod#1273]
### My Home Assistant Version

Core: 2026.05.0
Frontend: 20260429.3
Browser Mod: 2.12.0

### What I am doing

Calling the `browser_mod.popup` service from a script with the `user_id` parameter set fails on HA 2026.05 with:

```
AttributeError: module 'homeassistant.helpers.template' has no attribute 'state_attr'
```

The script worked previously but started failing after upgrading to 2026.05. Removing `user_id` from the popup call avoids the error and the popup displays normally.

### Minimal reproduction

Script action:

```yaml
- action: browser_mod.popup
  data:
    title: "Test"
    timeout: 5000
    dismissable: true
    autoclose: true
    user_id:
      - <user>
```

### Full traceback

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 532, in asyncstep
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1027, in asyncstep_call_service
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 642, in asyncrun_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2827, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2877, in executeservice
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/config/custom_components/browser_mod/service.py", line 103, in handle_browser_service
    userId = template.state_attr(hass, user, "user_id")
             ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.helpers.template' has no attribute 'state_attr'
```

### 

`browser_mod/service.py` line 103 calls `template.state_attr(hass, user, "user_id")` to resolve a person entity to a user ID. In HA 2026.05, `state_attr` is no longer accessible as a top-level attribute of `homeassistant.helpers.template`

### What I expect to happen

The `browser_mod.popup` service should display the popup on the targeted active browser sessions, as it did prior to 2026.05.

### What happened instead

The service call fails immediately with an `AttributeError`. No popup is displayed. The error is logged in `home-assistant.log` and surfaced in the script run history.

### Minimal steps to reproduce

1. Upgrade to Home Assistant 2026.05
2. Create a script (or automation) that calls `browser_mod.popup` with the `user_id` parameter set.
3. Run the script.
4. Remove the `user_id` parameter and re-run — the popup now displays correctly

### Include any yaml code here

```YAML
- action: browser_mod.popup
    metadata: {}
    data:
      dismissable: true
      autoclose: true
      allow_nested_more_info: true
      size: normal
      user_id:
        - <redacted>
      title: "{{ msg }}"
      timeout: "{{ delay }}"
```

### Error messages from the browser console

```console
no browser console error - appears to be server-side. Here's the error from the log though:

AttributeError: module 'homeassistant.helpers.template' has no attribute 'state_attr'
```

### By checking each box below I indicate that I ...

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
- [x] If this issue is to do with an Android device losing connection, sensors becoming unavailable etc., please confirm you have read, understood and tried methods described in Wiki Article [Andoird Devices 'Always On'](https://github.com/thomasloven/hass-browser_mod/wiki/Andoird-Devices-'Always-On')
